// ==============================
// THIS FILE IS AUTOMATICALLY GENERATED BY APP.
// DO NOT EDIT THIS FILE DIRECTLY.
// SEE: `/lib/page.js`
// SEE: `/lib/utils/syncPages.js`
// ==============================

/* eslint-disable */
import React from 'react'

import loadable from 'loadable-components'
import {
  wrapLoadable,
  renderLoadable
} from 'react-ur'

// Pages will be injected to here for better hmr support.
const PageBazFoo = loadable(async () => wrapLoadable(await import('./baz/foo')), { render: renderLoadable })
const PageNyan = loadable(async () => wrapLoadable(await import('./nyan')), { render: renderLoadable })
const PageBar = loadable(async () => wrapLoadable(await import('./bar')), { render: renderLoadable })
const PageBarHoge = loadable(async () => wrapLoadable(await import('./bar/hoge')), { render: renderLoadable })
const PageBaz = loadable(async () => wrapLoadable(await import('./baz')), { render: renderLoadable })
const PageFoo = loadable(async () => wrapLoadable(await import('./foo')), { render: renderLoadable })
  
export const Pages = {
  '/baz/foo': PageBazFoo,
  '/nyan': PageNyan,
  '/bar': PageBar,
  '/bar/hoge': PageBarHoge,
  '/baz': PageBaz,
  '/foo': PageFoo
}

export default Pages
